import type { RedditConversation } from "./types";

const hoursAgo = (h: number) => new Date(Date.now() - h * 36e5);

export const OUR_MOCK_USERNAME = "mock_foler_founder";

export const MOCK_CONVERSATIONS: RedditConversation[] = [
  {
    post: {
      id: "mockpost1",
      subreddit: "tressless",
      author: "mock_shedding_sam",
      title: "[MOCK] Anyone else shedding after starting minoxidil?",
      body: "Started minoxidil about 6 weeks ago and I'm seeing way more hairs in the shower drain. Is this normal? Getting a bit worried.",
      url: "https://www.reddit.com/r/tressless/comments/mockpost1/",
      createdAt: hoursAgo(30),
      numComments: 2,
    },
    comments: [
      {
        id: "mockc1a",
        postId: "mockpost1",
        parentId: null,
        subreddit: "tressless",
        author: "mock_veteran",
        body: "Yeah that's the dreaded shed, totally normal at week 6. It usually settles down.",
        url: "https://www.reddit.com/r/tressless/comments/mockpost1/#mockc1a",
        createdAt: hoursAgo(28),
      },
      {
        id: "mockc1b",
        postId: "mockpost1",
        parentId: null,
        subreddit: "tressless",
        author: "mock_helper",
        body: "Same thing happened to me. Push through it.",
        url: "https://www.reddit.com/r/tressless/comments/mockpost1/#mockc1b",
        createdAt: hoursAgo(20),
      },
    ],
  },
  {
    post: {
      id: "mockpost2",
      subreddit: "tressless",
      author: "mock_uncertain_uma",
      title: "[MOCK] 5 months on minoxidil and I honestly can't tell if my density changed",
      body: "Been on minoxidil for 5 months now. Some days I think it looks better, other days worse. I don't know if it's working and my photos aren't consistent enough to compare. How do you all judge progress?",
      url: "https://www.reddit.com/r/tressless/comments/mockpost2/",
      createdAt: hoursAgo(20),
      numComments: 1,
    },
    comments: [
      {
        id: "mockc2a",
        postId: "mockpost2",
        parentId: null,
        subreddit: "tressless",
        author: "mock_lurker",
        body: "Take pics every month under the same light.",
        url: "https://www.reddit.com/r/tressless/comments/mockpost2/#mockc2a",
        createdAt: hoursAgo(18),
      },
    ],
  },
  {
    post: {
      id: "mockpost3",
      subreddit: "HairlossResearch",
      author: "mock_measuring_mia",
      title: "[MOCK] How do you measure hair density at home? Comparing photos is a mess",
      body: "I want to objectively track my hair density over time. How do I measure it at home? I try comparing photos but the lighting and angle are never the same. Is there a reliable method or tool?",
      url: "https://www.reddit.com/r/HairlossResearch/comments/mockpost3/",
      createdAt: hoursAgo(12),
      numComments: 0,
    },
    comments: [],
  },
  {
    post: {
      id: "mockpost4",
      subreddit: "tressless",
      author: "mock_device_dan",
      title: "[MOCK] Is there any device or app that tracks hair density over time?",
      body: "Looking for a device or app that can measure/track hair density over time. I can't tell if anything is working and manual photo comparison is unreliable. Does something like this exist?",
      url: "https://www.reddit.com/r/tressless/comments/mockpost4/",
      createdAt: hoursAgo(50),
      numComments: 3,
    },
    comments: [
      {
        id: "mockc4a",
        postId: "mockpost4",
        parentId: null,
        subreddit: "tressless",
        author: OUR_MOCK_USERNAME,
        body: "Consistency matters more than the tool: same lighting, same angle, same distance each time, and keep your hair length roughly the same between photos.",
        url: "https://www.reddit.com/r/tressless/comments/mockpost4/#mockc4a",
        createdAt: hoursAgo(40),
      },
      {
        id: "mockc4b",
        postId: "mockpost4",
        parentId: "mockc4a",
        subreddit: "tressless",
        author: "mock_device_dan",
        body: "that makes sense, is there anything that does this automatically?",
        url: "https://www.reddit.com/r/tressless/comments/mockpost4/#mockc4b",
        createdAt: hoursAgo(30),
      },
    ],
  },
  {
    post: {
      id: "mockpost5",
      subreddit: "tressless",
      author: "mock_interested_ivy",
      title: "[MOCK] How are you all tracking whether your treatment is working?",
      body: "I can't tell if finasteride is doing anything after 4 months. How do you measure progress reliably?",
      url: "https://www.reddit.com/r/tressless/comments/mockpost5/",
      createdAt: hoursAgo(80),
      numComments: 4,
    },
    comments: [
      {
        id: "mockc5a",
        postId: "mockpost5",
        parentId: null,
        subreddit: "tressless",
        author: OUR_MOCK_USERNAME,
        body: "Same conditions every time is the big one. I'm actually working on something related to exactly this problem — would you be interested in hearing about it?",
        url: "https://www.reddit.com/r/tressless/comments/mockpost5/#mockc5a",
        createdAt: hoursAgo(60),
      },
      {
        id: "mockc5b",
        postId: "mockpost5",
        parentId: "mockc5a",
        subreddit: "tressless",
        author: "mock_interested_ivy",
        body: "Sure, what are you working on?",
        url: "https://www.reddit.com/r/tressless/comments/mockpost5/#mockc5b",
        createdAt: hoursAgo(50),
      },
      {
        id: "mockc5c",
        postId: "mockpost5",
        parentId: "mockc5b",
        subreddit: "tressless",
        author: OUR_MOCK_USERNAME,
        body: "We're building FOLĒR — it's focused on making hair and scalp changes more measurable over time. Still early, not public yet.",
        url: "https://www.reddit.com/r/tressless/comments/mockpost5/#mockc5c",
        createdAt: hoursAgo(40),
      },
      {
        id: "mockc5d",
        postId: "mockpost5",
        parentId: "mockc5c",
        subreddit: "tressless",
        author: "mock_interested_ivy",
        body: "That sounds really useful, where can I sign up?",
        url: "https://www.reddit.com/r/tressless/comments/mockpost5/#mockc5d",
        createdAt: hoursAgo(30),
      },
    ],
  },
  {
    post: {
      id: "mockpost6",
      subreddit: "HairlossResearch",
      author: "mock_signedup_stu",
      title: "[MOCK] Finally found a consistent way to track progress",
      body: "After struggling to compare photos for months I found something promising.",
      url: "https://www.reddit.com/r/HairlossResearch/comments/mockpost6/",
      createdAt: hoursAgo(100),
      numComments: 2,
    },
    comments: [
      {
        id: "mockc6a",
        postId: "mockpost6",
        parentId: null,
        subreddit: "HairlossResearch",
        author: OUR_MOCK_USERNAME,
        body: "Glad it resonates. We're opening the early waitlist here if you'd like to take a look.",
        url: "https://www.reddit.com/r/HairlossResearch/comments/mockpost6/#mockc6a",
        createdAt: hoursAgo(90),
      },
      {
        id: "mockc6b",
        postId: "mockpost6",
        parentId: "mockc6a",
        subreddit: "HairlossResearch",
        author: "mock_signedup_stu",
        body: "Just signed up for the waitlist, thanks!",
        url: "https://www.reddit.com/r/HairlossResearch/comments/mockpost6/#mockc6b",
        createdAt: hoursAgo(80),
      },
    ],
  },
];
